name: arabic_commonvoice_v10.0
train_ds_manifest_path: /dataset/processed/wav_16k/train/train_manifest.json
dev_ds_manifest_path: /dataset/processed/wav_16k/dev/dev_manifest.json
test_ds_manifest_path: /dataset/processed/wav_16k/test/test_manifest.json
