# name is based on the test dataset used
name: arabic_commonvoice_v10.0

# train data is tusni_msa + mediaspeech + common voice
train_clearml_id: 4af474c3645143daaaf5b29bc79a6330
# dev data is common voice only
dev_clearml_id: 104f6e9443784fa8b609c3a55ea1d3aa
# test data is common voice only
test_clearml_id: 26f6fc1946964341af30bfee6a04b3bf

train_ds_manifest_path: ???
dev_ds_manifest_path: ???
test_ds_manifest_path: ???

remove_unused_chars: true
threshold: 50