name: arabic_commonvoice_v10.0

train_clearml_id: 709a1943cd0c4db18ec32cb17d978541
dev_clearml_id: aed67512dedf488da268fd1e21d0acd6
test_clearml_id: 7a78d05734d542efa6d8e43989349be1

train_ds_manifest_path: ???
dev_ds_manifest_path: ???
test_ds_manifest_path: ???
