hydra:
  run:
    dir: '.'

early_stopping:
  patience: 20

task_type: training

defaults:
  - dataset: local_arabic_cv
  # - tokenizer: local_bpe1024
  - pretrained_model: conformer_large_bpe_ctc_1_10
  - nemo: conformer_large_bpe_ctc

name: ${nemo.name}_${dataset.name}