hydra:
  run:
    dir: '.'
#set to training for training and testing for testing
task_type: testing

early_stopping:
  patience: 20

#set tokenizer to local_bpe for training, trained_bpe for testing. Also, add the task id to trained_bpe yaml file
defaults:
  - dataset: remote_indo_cv
  - tokenizer: trained_bpe128
  - pretrained_model: remote_conformer_ctc_small_id
  - nemo: conformer_small_bpe_ctc

name: ${nemo.name}_${dataset.name}

#put project_name as nemo_asr/${dataset.name}/test when doing testing, else put nemo_asr/${dataset.name}
clearml:
  base_docker_image: dleongsh/nemo:1.10.0
  project_name: nemo_asr/${dataset.name}/test
  task_name: ${nemo.name}
  output_uri: s3://experiment-logging/storage
  queue_name: compute